# Generated by Django 3.1 on 2021-12-05 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fax',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Enter correct number start with +', regex='^\\+\\d+$')], verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_phone',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Enter correct number start with +', regex='^\\+\\d+$')], verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter correct number start with +', regex='^\\+\\d+$')], verbose_name='Личный телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
